name: acropolis_member_management
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firestore_search: ^0.1.3
  firebase_core: ^1.4.0
  firebase_auth_web: ^3.0.0
  cloud_firestore: ^2.2.2
  provider: ^4.3.2+2
  uuid: ^3.0.1
  intl: ^0.17.0
  #get: ^4.1.4
  get: ^3.24.0
  font_awesome_flutter: ^9.0.0
  qr_code_scanner: ^0.4.0
  audioplayers: ^0.20.1
  glassmorphism: ^2.0.1
  flutter_fadein: ^2.0.0
  firebase_auth: ^3.0.1
  shared_preferences: ^2.0.6
  font_awesome: ^5.10.1
  min_id: ^1.1.0
  url_launcher: ^6.0.3
  flutter_grid_button: ^2.0.0
  flutter_datetime_picker: ^1.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
dependency_overrides:
  intl: 0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/main_logo.png
   - assets/AcropolisLogo.jpg
   - assets/imageMe.png
   - assets/AcropolisWhiteLogo.png

#Merch 
 # - clothes
   - assets/market/clothes/blackCropTop.jpg
   - assets/market/clothes/blackShirt.jpg
   - assets/market/clothes/greenShirt.jpg
   - assets/market/clothes/lightCropTop.jpg
   - assets/market/clothes/whiteCropTop.jpg
   - assets/market/clothes/whiteShirt.jpg


  # - Food
   - assets/market/food/BangP.png
   - assets/market/food/DasaniWater.jpg
   - assets/market/food/PoweradeL.png
   - assets/market/food/PoweradeO.png
   - assets/market/food/PoweradeP.png
   - assets/market/food/LeanShakeC.jpg
   - assets/market/food/LeanShakeV.jpg
   - assets/market/food/MonsterR.jpg
   - assets/market/food/MonsterBlue.jpg
   - assets/market/food/ProteinBar.jpg
   - assets/market/food/GNCC.jpeg
   - assets/market/food/GNCV.jpeg
   - assets/market/food/Reign.jpg
   - assets/market/food/towelL.jpg
   - assets/market/food/towelS.jpg
   - assets/AcropolisWallpaper.png

   # - Sound Effects

   - assets/ScanSound.mp3
   - assets/successfulCheckIn.mp3
   - assets/notSuccessfulCheckIn.mp3

    
#Fonts
  fonts:
   - family: Edo
     fonts:
     - asset: assets/fonts/edo.ttf
   - family: Neuton
     fonts:
      - asset: assets/fonts/Neuton/Neuton-Regular.ttf

   - family: Sans
     fonts:
      - asset: assets/fonts/Source_Sans_Pro/SourceSansPro-Regular.ttf
      
#Icons
   - family: AcropolisIcon
     fonts:
     - asset: assets/fonts/icons/AcropolisIcon.ttf

   - family: MaskIcon
     fonts:
     - asset: assets/fonts/icons/MaskIcon.ttf

   - family: DealsIcon
     fonts:
     - asset: assets/fonts/icons/dealsIcon.ttf

   - family: trainerIcon
     fonts:
     - asset: assets/fonts/icons/trainerIcon.ttf

   - family: memberID
     fonts:
     - asset: assets/fonts/icons/memberID.ttf

   - family: QrIcon
     fonts:
     - asset: assets/fonts/icons/QrIcon.ttf

   - family: instagramIcon
     fonts:
     - asset: assets/fonts/icons/InstagramIcon.ttf

   - family: heightIcon
     fonts:
     - asset: assets/fonts/icons/heightIcon.ttf

   - family: FlyerIcon
     fonts:
     - asset: assets/fonts/icons/FlyerIcon.ttf

   - family: InventoryIcon
     fonts:
     - asset: assets/fonts/icons/InventoryIcon.ttf

   - family: POSIcon
     fonts:
     - asset: assets/fonts/icons/POSIcon.ttf

   - family: PayWithCardIcon
     fonts:
     - asset: assets/fonts/icons/PayWithCardIcon.ttf

   - family: instagramIcon
     fonts:
     - asset: assets/Icons/InstagramIcon.ttf
     
   - family: QrScanIcon
     fonts:
     - asset: assets/fonts/icons/QrScanIcon.ttf

   - family: TapHereIcon
     fonts:
     - asset: assets/fonts/icons/tapHereIcon.ttf

   - family: TypingIcon
     fonts:
     - asset: assets/fonts/icons/typingIcon.ttf



