
import 'package:acropolis_member_management/FirebaseBackend/services/MemberClass.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

class FirestoreHistory {
  FirebaseFirestore _dbhistory = FirebaseFirestore.instance;

Stream<List<InventoryInformation>> getJune252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJune262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJune272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJune282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJune292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJune302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "June 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

Stream<List<InventoryInformation>> getJuly12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getJuly312021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "July 31, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

// August

Stream<List<InventoryInformation>> getAugust12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getAugust312021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "August 31, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

//September

Stream<List<InventoryInformation>> getSeptember12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getSeptember312021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "September 31, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

//October

Stream<List<InventoryInformation>> getOctober12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getOctober312021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "October 31, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

//November

Stream<List<InventoryInformation>> getNovember12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getNovember302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "November 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}

//December

Stream<List<InventoryInformation>> getDecember12021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 1, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember22021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 2, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember32021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 3, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember42021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 4, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember52021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 5, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember62021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 6, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember72021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 7, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember82021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 8, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember92021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 9, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember102021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 10, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember112021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 11, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember122021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 12, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember132021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 13, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember142021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 14, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember152021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 15, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember162021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 16, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember172021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 17, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember182021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 18, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember192021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 19, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember202021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 20, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember212021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 21, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember222021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 22, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember232021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 23, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember242021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 24, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember252021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 25, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember262021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 26, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember272021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 27, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember282021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 28, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember292021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 29, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember302021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 30, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}
Stream<List<InventoryInformation>> getDecember312021() {return _dbhistory.collection('InventoryLogs').where('inventoryDate', isEqualTo: "December 31, 2021").orderBy('inventoryTime',descending: true ).snapshots().map((snapshot) => snapshot.docs.map((document) => InventoryInformation.fromFirestore(document.data())).toList());}


}
